apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glowroot.fullname" . }}-extra-config
  labels:
    {{- include "glowroot.labels" . | nindent 4 }}
data:
  extra-config.sh: |
    #!/usr/bin/env bash

    {{- if .Values.glowroot.extraInitConfig }}
    {{ .Values.glowroot.extraInitConfig }}
    {{- end }}
  