apiVersion: v2
name: glowroot
description: Helm chart for glowroot
type: application
version: 1.0.0
appVersion: 0.13.7

maintainers:
  - name: Lucas Hahn 
    email: lucas.hahn@novum-rgi.de

dependencies:
- name: cassandra
  repository: https://charts.bitnami.com/bitnami
  version: 5.5.0
