apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependency-track.fullname" . }}-config
  labels:
    {{- include "dependency-track.labels" . | nindent 4 }}
type: Opaque
stringData: |
  {{- if not (hasKey .Values.dependencyTrack.config.alpine "database") -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine "database" dict -}}
  {{- end -}}

  {{- if .Values.dependencyTrack.database.builtIn.postgresql.enabled -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "mode"         "external" -}} 
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "url"          (printf "jdbc:postgresql://%s" (include "postgresql.dns" .)) -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "driver"       "org.postgresql.Driver" -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "driverPath"   "/extlib/postgresql-42.2.5.jar" -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "username"     .Values.postgresql.global.postgresql.postgresqlUsername -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "password"     .Values.postgresql.global.postgresql.postgresqlPassword -}}
  {{ else if .Values.dependencyTrack.database.builtIn.mysql.enabled -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "mode"         "external" -}} 
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "url"          printf "jdbc:mysql://%s" (include "mysql.dns" .) -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "driver"       "com.mysql.jdbc.Driver" -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "driverPath"   "/extlib/mysql-connector-java-5.1.45-bin.jar" -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "username"     .Values.mysql.db.name -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "password"     .Values.mysql.db.password -}}
  {{ else if .Values.dependencyTrack.database.builtIn.mariadb.enabled -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "mode"         "external" -}} 
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "url"          printf "jdbc:mysql://%s" (include "mariadb.dns" .) -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "driver"       "com.mysql.jdbc.Driver" -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "driverPath"   "/extlib/mysql-connector-java-5.1.45-bin.jar" -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "username"     .Values.mariadb.db.user -}}
  {{- $_ := set .Values.dependencyTrack.config.alpine.database "password"     .Values.mariadb.db.password -}}
  {{- end -}}
  
  {{- /* autogenerate config */ -}}
  {{ include "dependency-track.configParse" (dict "data" .Values.dependencyTrack.config "currentName" "") | nindent 4 }}
  