apiVersion: v1
kind: Service
metadata:
  name: {{ include "awx.fullname" . }}
  labels:
    {{- include "awx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http 
      port: {{ .Values.service.port }}
      targetPort: 8052
  selector:
    {{- include "awx.selectorLabels" . | nindent 4 }}
