# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gitea/gitea
  version: 1.12.2
  pullPolicy: Always

imagePullSecrets: []

service:
  http:
    type: ClusterIP
    port: 3000
  ssh:
    type: ClusterIP
    port: 22
    #loadBalancerIP:
    #nodePort:
    annotations:

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - git.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

statefulset:
  terminationGracePeriodSeconds: 60

persistence:
  enabled: true
  # existingClaim: 
  size: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClass: standard

gitea:
  config:
    appName: "Gitea: Git with a cup of tea"
    runMode: dev
    # Do not change the run user for gitea default container
    runUser: git

    adminUser: "gitea_admin"
    adminPassword: "gitea123456"
    adminEmail: "example@gitea.com"

  ldap:
    enabled: false
    name: ""
    securityProtocol: ""
    host: ""
    port: ""
    userSearchBase: ""
    userFilter: ""
    adminFilter: ""
    emailAttribute: ""
    bindDn: ""
    bindPassword: ""
    usernameAttribute: ""

  server:
    http:
      externalDomain: git.example.com
      externalPort:
    ssh:
      externalDomain: git.example.com
      externalPort:
    offlineMode: false

  repository:
    root:
    forcePrivate: false
    defaultPrivate: last
    maxCreationLimit: -1
    mirrorQueueLength: 1000
    pullRequestQueueLength: 1000
    preferredLicenses: Apache License 2.0,MIT License
    disableHttpGit: false
    useCompatSSHUri: false

    local:
      copyPath: tmp/local-repo
      wikiPath: tmp/local-wiki

    upload:
      enabled: true
      tempPath: data/tmp/uploads
      allowedTypes:
      fileMaxSize: 3
      maxFiles: 5

    pullRequest:
      workInProgressPrefixes: "WIP:,[WIP]"
      closeKeywords: close,closes,closed,fix,fixes,fixed,resolve,resolves,resolved
      reopenKeywords: reopen,reopens,reopened
      defaultMergeMessageCommitsLimit: 50
      defaultMergeMessageSize: 5120
      defaultMergeMessageAllAuthors: false
      defaultMergeMessageMaxApprovers: 10
      defaultMergeMessageOfficialApproversOnly: true

    signing:
      signingKey: default
      signingName:
      signingEmail:
      initialCommit: always
      crudActions: pubkey, twofa, parentsigned
      wiki: never
      merges: pubkey, twofa, basesigned, commitssigned

  ui:
    explorePagingNum: 20
    issuePagingNum: 10
    membersPagingNum: 20
    feedMaxCommitNum: 5
    graphMaxCommitNum: 100
    codeCommentLines: 4
    themeColorMetaTag: "#6cc644"
    maxDisplayFileSize: 8388608
    defaultTheme: gitea
    showUserMail: true
    defaultShowFullName: false
    searchRepoDescription: true
    useServiceWorker: true

  database:
    builtIn:
      postgresql:
        enabled: true
      mysql:
        enabled: false

    external:
      type: postgres
      port: 5432
      host:
      name: gitea
      user: gitea
      password: gitea
      schema:

    sslMode: disable
    charset: utf8mb4
    path: data/gitea.db
    sqlLiteTimeout: 500
    iterateBufferSize: 50
    logSql: true
    dbRetries: 10
    dbRetryBackoff: 3s
    maxIdleConns: 2
    connMaxLifetime: 3s
    maxOpenConns: 0

  admin:
    disableRegularOrgCreation: false
    defaultEmailNotifications: enabled

  security:
    installLock: true
    secretKey: "!#@FDEWREWR&*("
    loginRememberDays: 7
    cookieUsername: gitea_awesome
    cookieRememberName: gitea_incredible
    reverseProxyAuthUser: X-WEBAUTH-USER
    reverseProxyAuthEmail: X-WEBAUTH-EMAIL
    minPasswordLength: 6
    importLocalPaths: false
    disabledGitHooks: false
    onlyAllowPushIfGiteaEnvSet: true
    passwordComplexity: "off"
    passwordHashAlgo: pbkdf2
    crsfCookieHttpOnly: true

  openid:
    enableOpenidSignin: true
    enableOpenidSignup: true
    whitelistedUris:
    blacklistedUris:

  service:
    activeCodeLiveMinutes: 180
    resetPasswordCodeLiveMinutes: 180
    registerEmailConfirm: false
    emailDomainWhitelist:
    disableRegistration: false
    allowOnlyExternalRegistration: false
    requireSigninView: false
    enableNotifyMail: false
    enableBasicAuth: true
    enableReverseProxyAuth: false
    enableReverseProxyAutoRegistration: false
    enableReverseProxyEmail: false
    enableCaptcha: false
    captchaType: image
    recaptchaSecret:
    recaptchaSiteKey:
    racaptchaUrl: https://www.google.com/recaptcha/
    defaultKeepEmailPrivate: false
    deaultAllowCreateOrg: true
    defaultOrgVisibility: public
    defaultOrgMemberVisible: false
    defaultEnableDependencies: true
    allowCrossRepositoryDependencies: true
    enableUserHeatmap: true
    enableTimeTracking: true
    defaultEnableTimeTracking: true
    defaultAllowOnlyContributorsToTrackTime: true
    noReplyAddress: noreply.example.org
    showRegistrationButton: true
    showMilestonesDashboardPage: true
    autoWatchNewRepos: true
    autoWatchOnChanges: false

  webhook:
    queueLength: 1000
    deliverTimeout: 5
    skipTlsVerify: false
    pagingNum: 10

  mailer:
    enabled: false
    sendBufferLen: 100
    subjectPrefix:
    host:
    disableHelo:
    heloHostname:
    skipVerify:
    useCertificate: false
    certFile: custom/mailer/cert.pem
    keyFile: custom/mailer/key.pem
    isTlsEnabled: false
    from:
    user:
    password:
    sendAsPlainText: false
    mailerType: smtp
    sendMailPath: sendmail
    sendMailArgs:
    sendMailTimeout: 5m

  cache:
    enabled: true

    builtIn:
      enabled: true

    external:
      adapter: memory
      host:

    interval: 60
    itemTTL: 16h

    lastCommit:
      enabled: true
      itemTTL: 8760h
      commitCount: 1000

  attachment:
    enabled: true
    path: data/attachments
    allowedTypes: image/jpeg|image/png|application/zip|application/gzip
    maxSize: 4
    maxFiles: 5

  log:
    rootPath:
    mode: console
    bufferLen: 10000
    redirectMacaronLog: false
    macaron: file
    routerLogLevel: Info
    router: console
    enableAccessLog: false
    access: file
    level: Info
    stackTraceLevel: None

    x:
      flags: stdflags
      expression:
      prefix:
      colorize: false

    console:
      level: None
      stderr: false

    file:
      level: None
      fileName:
      logRotate: true
      maxLines: 100000
      maxSizeShift: 28
      dailyRotate: true
      maxDays: 7
      compress: true
      compressionLeveL: -1

    conn:
      level: None
      reconnOnMsg: false
      reconnect: false
      protocol: tcp
      addr:

    smtp:
      level: None
      subject: Diagnostic message from server
      host:
      user:
      password:
      receivers:

  git:
    path:
    disableDiffHighlight: false
    maxGitDiffLines: 1000
    maxGitDiffLineChars: 5000
    maxGitDiffFiles: 100
    gcArgs:
    enableAutoGitWireProt: true
    pullRequestPushMessage: true

    timeout:
      default: 360
      migrate: 600
      mirror: 300
      clone: 300
      pull: 300
      gc: 60
  metrics:
    enabled: false
    token:
  extraConfig:

memcached:
  service:
    port: 11211

postgresql:
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  persistence:
    size: 10Gi

mysql:
  mysqlRootPassword: gitea
  mysqlUser: gitea
  mysqlPassword: gitea
  mysqlDatabase: gitea
  service:
    port: 3306
  persistence:
    size: 10Gi
