apiVersion: v2
name: dependency-track
description: Dependency Track helm chart
type: application
version: 0.1.8
appVersion: 3.8.0
home: https://dependencytrack.org/
icon: https://github.com/DependencyTrack/branding/blob/master/dt-logo-black-text.svg

keywords:
 - security
 - dependency
 - dependency-track
 - OWASP
 - Supply Chain Component Analysis
 
sources:
  - https://github.com/novumrgi/helm
  - https://github.com/DependencyTrack/dependency-track
  - https://hub.docker.com/r/owasp/dependency-track

maintainers:
  - name: Lucas Hahn
    email: lucas.hahn@novum-rgi.de

dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 9.7.2
  condition: dependencyTrack.database.builtIn.postgresql.enabled
