apiVersion: v2
name: dependency-track
description: Dependency Track helm chart
type: application
version: 0.1.3
appVersion: 3.8.0

sources:
  - https://github.com/novumrgi/helm
  - https://github.com/DependencyTrack/dependency-track
  - https://hub.docker.com/r/owasp/dependency-track

maintainers:
  - name: Lucas Hahn
    email: lucas.hahn@novum-rgi.de

dependencies:
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 6.14.10
  condition: gitea.database.builtIn.mysql.enabled
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 9.7.2
  condition: gitea.database.builtIn.postgresql.enabled
- name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 7.10.2
  condition: gitea.database.builtIn.mariadb.enabled