apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitea.fullname" . }}-ssh
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.service.ssh.annotations | indent 4 }}
spec:
  type: {{ .Values.service.ssh.type }}
  {{- if and .Values.service.ssh.loadBalancerIP (eq .Values.service.ssh.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.ssh.loadBalancerIP }}
  {{- end }}
  clusterIP: None
  ports:
  - name: ssh
    port: {{ .Values.service.ssh.port }}
    targetPort: ssh
    protocol: TCP
    {{- if  .Values.service.ssh.nodePort }}
    nodePort: {{ .Values.service.ssh.nodePort }}
    {{- end }}
  selector:
    {{- include "gitea.selectorLabels" . | nindent 4 }}
