{{- if .Values.ingress.agent.enabled -}}
{{- $fullName := include "glowroot.fullname" . -}}
{{- $agentPort := .Values.service.agentPort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-agent
  labels:
    {{- include "glowroot.labels" . | nindent 4 }}
  {{- with .Values.ingress.agent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.agent.tls }}
  tls:
  {{- range .Values.ingress.agent.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.agent.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $agentPort }}
  {{- end }}
{{- end }}
